apiVersion: apps/v1
kind: Deployment
metadata:
  name: <repo>
  labels:
    app: <repo>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <repo>
  template:
    metadata:
      labels:
        app: <repo>
    spec:
      containers:
        - name: <repo>
          image: aicollaboration/<repo>:30dd49434c7f53966006fb2dacdd7a326c169b6c
          imagePullPolicy: Always
          env:
          - name: PYTHONUNBUFFERED
            value: "0"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "2048Mi"
              cpu: "500m"
      restartPolicy: Always
