apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-answering
  labels:
    app: question-answering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-answering
  template:
    metadata:
      labels:
        app: question-answering
    spec:
      containers:
        - name: question-answering
          image: aicollaboration/question-answering:30dd49434c7f53966006fb2dacdd7a326c169b6c
          imagePullPolicy: Always
          env:
          - name: PYTHONUNBUFFERED
            value: "0"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "2048Mi"
              cpu: "500m"
      restartPolicy: Always
