version: '3'
services:
  question-answering:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5060:5000
    environment:
      PYTHONUNBUFFERED: 1
    volumes: 
      - ".:/app"
