openapi: 3.1.0
info:
  title: Micro model service for questions answering
  version: 1.0.0
  description: It will use a pretrained bert
servers:
  - url: https://demos.deepset.ai
paths: 
  /models/2/inference:
    post:
      operationId: inference
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Input"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Output"

components:
  schemas:
    Input:
      type: object
      properties:
        context:
          type: string
          description: The text you want to search in
        question:
          type: string
    Output:
      type: object
      properties:
        answer:
          type: string
